In [1]:
import json
from itertools import chain
from math import ceil

from keras.preprocessing.image import ImageDataGenerator
import numpy as np
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

/home/ubuntu/anaconda2/envs/fashion/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
from keras.applications.resnet50 import ResNet50
from keras import losses
from keras.layers import Flatten, Dense, Dropout
from keras.layers.normalization import BatchNormalization

In [3]:
from keras import Model
from sklearn.model_selection import train_test_split

In [4]:
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint

## Load ResNet model

In [5]:
base_model = ResNet50(weights='imagenet', include_top = False, input_shape=(224, 224, 3))

In [14]:
# print(base_model.summary())

In [15]:
label_count=227

In [16]:
x = Flatten()(base_model.output)
x = Dense(4096, activation='relu')(x)
x = Dropout(0.5)(x)
x = BatchNormalization()(x)
predictions = Dense(label_count, activation = 'sigmoid')(x)

In [17]:
head_model = Model(input = base_model.input, output = predictions)

/home/ubuntu/anaconda2/envs/fashion/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  if __name__ == '__main__':


In [18]:
head_model.load_weights('results/best_weights.hdf5')

In [19]:
head_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
head_model.output_shape

(None, 227)

## Go through test images and predict

In [36]:
batch_size = 100
gen_test = ImageDataGenerator().flow_from_directory('images_test',
                                                    target_size=(224, 224),
                                                    class_mode=None, 
                                                    shuffle=False,
                                                    batch_size=batch_size)
num_images_test = len(gen_test.filenames)

Found 39706 images belonging to 1 classes.


In [37]:
img_ids_test_all = np.array([int(fn[5:-4]) for fn in gen_test.filenames])
img_ids_test_all.shape

(39706,)

### first 1k

In [56]:
test_chunks = []
test_id_chunks = []

In [57]:
num_images_test = 1000

start_batch = 0
batches = []
for i in range(ceil(num_images_test / gen_test.batch_size)):
    batches.append(gen_test.next())
    
img_arrays_test = np.array(list(chain(*batches)))
del batches
img_arrays_test = img_arrays_test[:num_images_test]

test_chunks.append(img_arrays_test)


In [58]:
i

9

In [60]:
test_id_chunks.append(
    img_ids_test_all[start_batch * batch_size: 
                     start_batch * batch_size + num_images_test]
)


In [61]:
test_id_chunks

[array([    1,    10,   100,  1000, 10000, 10001, 10002, 10003, 10004,
        10005, 10006, 10007, 10008, 10009,  1001, 10010, 10011, 10012,
        10013, 10014, 10015, 10016, 10017, 10018, 10019,  1002, 10020,
        10021, 10022, 10023, 10024, 10025, 10026, 10027, 10028, 10029,
         1003, 10030, 10031, 10032, 10033, 10034, 10035, 10036, 10037,
        10038, 10039,  1004, 10040, 10041, 10042, 10043, 10044, 10045,
        10046, 10047, 10048, 10049,  1005, 10050, 10051, 10052, 10053,
        10054, 10055, 10056, 10057, 10058, 10059,  1006, 10060, 10061,
        10062, 10063, 10064, 10065, 10066, 10067, 10068, 10069,  1007,
        10070, 10071, 10072, 10073, 10074, 10075, 10076, 10077, 10078,
        10079,  1008, 10080, 10081, 10082, 10083, 10084, 10085, 10086,
        10087, 10088, 10089,  1009, 10090, 10091, 10092, 10093, 10094,
        10095, 10096, 10097, 10098, 10099,   101,  1010, 10100, 10101,
        10102, 10103, 10104, 10105, 10106, 10107, 10108, 10109,  1011,
      

In [63]:
prediction_chunks = []

In [65]:
%%time
prediction_chunks.append(head_model.predict(test_chunks[0]))

CPU times: user 20min 54s, sys: 1min 45s, total: 22min 39s
Wall time: 6min 11s


In [67]:
prediction_chunks[0].shape

(100, 227)

In [ ]:
num_images_test = 1000

start_batch = 1
batches = []
for i in range(ceil(num_images_test / gen_test.batch_size)):
    batches.append(gen_test.next())
    
img_arrays_test = np.array(list(chain(*batches)))
del batches
img_arrays_test = img_arrays_test[:num_images_test]

test_chunks.append(img_arrays_test)


## 2nd loop attempt

In [83]:
batch_size = 32
gen_test = ImageDataGenerator().flow_from_directory('images_test',
                                                    target_size=(224, 224),
                                                    class_mode=None, 
                                                    shuffle=False,
                                                    batch_size=batch_size)

Found 39706 images belonging to 1 classes.


In [84]:
num_images_test = len(gen_test.filenames)
num_images_test

39706

In [85]:
img_ids_test_all = np.array([int(fn[5:-4]) for fn in gen_test.filenames])
img_ids_test_all.shape

(39706,)

In [88]:
chunked_predictions = []
chunked_img_ids = []

for i in range(ceil(num_images_test / gen_test.batch_size)):
    print(i)
    batch = gen_test.next()
    predictions = head_model.predict(batch)
    img_ids = img_ids_test_all[i * gen_test.batch_size : (i + 1) * gen_test.batch_size]
    chunked_predictions.append(predictions)
    chunked_img_ids.append(img_ids)
    if i >= 5:
        print('breaking')
        break


0
1
2
3
4
5
breaking


In [93]:
np.array(chunked_predictions).shape

(6, 32, 227)

In [91]:
np.array(chunked_img_ids).shape

(6, 32)

In [95]:
chunked_predictions[0]

array([0.01547124, 0.0450897 , 0.02162396, 0.03189637, 0.03580599,
       0.03269533, 0.03607636, 0.57041144, 0.2762965 , 0.01618437,
       0.02135538, 0.04706649, 0.01934328, 0.0767343 , 0.02671728,
       0.02297901, 0.01805874, 0.02229851, 0.0311577 , 0.71278363,
       0.0423255 , 0.04711476, 0.04254869, 0.02227439, 0.00928177,
       0.04010453, 0.17350438, 0.02189047, 0.03521808, 0.02693619,
       0.05884839, 0.03063242, 0.02176283, 0.0453779 , 0.02936278,
       0.03961569, 0.05542257, 0.03927505, 0.03291159, 0.04870011,
       0.04502208, 0.03378347, 0.11730143, 0.09574386, 0.03419983,
       0.02141596, 0.0201642 , 0.0469939 , 0.02543291, 0.03820044,
       0.06821832, 0.07181704, 0.01966202, 0.03039076, 0.06224285,
       0.02741141, 0.02015221, 0.06761385, 0.08629825, 0.07163592,
       0.6772691 , 0.02436218, 0.0249885 , 0.0388895 , 0.0323426 ,
       0.02882665, 0.03848581, 0.02242135, 0.04464923, 0.06055853,
       0.06898058, 0.5438623 , 0.05337121, 0.03407285, 0.08674

In [117]:
combined = pd.concat([pd.DataFrame(pred) for pred in chunked_predictions])
combined.index = np.concatenate(chunked_img_ids)
combined.columns = range(1, 1 + len(combined.columns))
combined

1         2         3         4         5         6         7    \
1      0.015471  0.045090  0.021624  0.031896  0.035806  0.032695  0.036076   
10     0.014402  0.028376  0.011889  0.019857  0.012750  0.051179  0.023252   
100    0.011814  0.022332  0.016337  0.021459  0.006230  0.023783  0.060604   
1000   0.007304  0.012954  0.024639  0.013152  0.010992  0.027407  0.030604   
10000  0.005094  0.015215  0.016866  0.011703  0.010637  0.057631  0.013181   
10001  0.005691  0.012119  0.017751  0.008929  0.012027  0.021677  0.008019   
10002  0.004984  0.052278  0.045735  0.056658  0.032421  0.036652  0.034357   
10003  0.005563  0.014714  0.013420  0.027383  0.021803  0.028117  0.016118   
10004  0.010940  0.038539  0.019544  0.031600  0.030570  0.060299  0.018424   
10005  0.008421  0.031258  0.014648  0.017064  0.028346  0.070627  0.020682   
10006  0.012186  0.017007  0.023791  0.024785  0.012812  0.026175  0.025298   
10007  0.015118  0.012322  0.019079  0.010909  0.016977  0.047179  0.031172   
10008  0.008531  0.016798  0.010919  0.015951  0.022312  0.015507  0.018803   
10009  0.011054  0.038553  0.022552  0.066180  0.034759  0.036421  0.024683   
1001   0.006898  0.011963  0.012334  0.015331  0.015226  0.013870  0.025033   
10010  0.005375  0.016719  0.008175  0.024360  0.015913  0.036392  0.022193   
10011  0.012371  0.018876  0.037434  0.022436  0.033705  0.019423  0.019392   
10012  0.007436  0.021610  0.010859  0.012739  0.011274  0.016921  0.020966   
10013  0.007772  0.015550  0.020390  0.011091  0.017397  0.033641  0.014635   
10014  0.004680  0.006927  0.010232  0.006365  0.012266  0.013646  0.013942   
10015  0.011480  0.039520  0.019923  0.028845  0.036040  0.045039  0.035302   
10016  0.005547  0.031990  0.020845  0.009461  0.009938  0.081861  0.015930   
10017  0.010224  0.027304  0.023555  0.038481  0.022661  0.032740  0.016213   
10018  0.012499  0.024084  0.030050  0.016341  0.019578  0.028829  0.022347   
10019  0.003467  0.015049  0.010428  0.013823  0.011394  0.015564  0.015881   
1002   0.004200  0.018818  0.017787  0.010903  0.017051  0.034321  0.035315   
10020  0.006936  0.030584  0.006168  0.039484  0.024421  0.010921  0.030229   
10021  0.012435  0.014433  0.016474  0.032643  0.017788  0.014159  0.032160   
10022  0.011198  0.016924  0.015297  0.015860  0.017699  0.035443  0.020559   
10023  0.009615  0.011944  0.015929  0.035639  0.041731  0.018353  0.019098   
...         ...       ...       ...       ...       ...       ...       ...   
10143  0.007930  0.026795  0.008741  0.080450  0.010929  0.027050  0.017386   
10144  0.012089  0.020315  0.010825  0.058629  0.024110  0.026787  0.045979   
10145  0.006760  0.012972  0.012711  0.011203  0.009577  0.022145  0.009247   
10146  0.006757  0.026374  0.014805  0.011571  0.018068  0.053232  0.028895   
10147  0.008485  0.017738  0.010067  0.017019  0.021013  0.062743  0.018654   
10148  0.003375  0.014973  0.022426  0.010829  0.014107  0.032270  0.017473   
10149  0.004670  0.012903  0.009264  0.023732  0.008592  0.012267  0.016735   
1015   0.006427  0.008288  0.021169  0.007778  0.012237  0.020197  0.012285   
10150  0.007483  0.012650  0.040634  0.019378  0.009430  0.051109  0.016275   
10151  0.008227  0.020644  0.041362  0.010615  0.014170  0.022612  0.010898   
10152  0.007231  0.021413  0.019821  0.013295  0.017011  0.010578  0.014755   
10153  0.009080  0.010566  0.018179  0.015465  0.015499  0.025216  0.017947   
10154  0.008734  0.018499  0.014936  0.020915  0.020956  0.035599  0.021665   
10155  0.013599  0.014260  0.017053  0.017141  0.010900  0.025422  0.037278   
10156  0.007226  0.083269  0.009802  0.092463  0.014845  0.085165  0.017516   
10157  0.004743  0.044670  0.006156  0.103362  0.038570  0.027191  0.027212   
10158  0.007650  0.032061  0.011357  0.018492  0.017471  0.023497  0.013161   
10159  0.006043  0.010172  0.009780  0.004858  0.008316  0.026557  0.027776   
1016   0.004110  0.016417  0.048033  0.013460  0.022119  0.016

[array([    1,    10,   100,  1000, 10000, 10001, 10002, 10003, 10004,
        10005, 10006, 10007, 10008, 10009,  1001, 10010, 10011, 10012,
        10013, 10014, 10015, 10016, 10017, 10018, 10019,  1002, 10020,
        10021, 10022, 10023, 10024, 10025]),
 array([10026, 10027, 10028, 10029,  1003, 10030, 10031, 10032, 10033,
        10034, 10035, 10036, 10037, 10038, 10039,  1004, 10040, 10041,
        10042, 10043, 10044, 10045, 10046, 10047, 10048, 10049,  1005,
        10050, 10051, 10052, 10053, 10054]),
 array([10055, 10056, 10057, 10058, 10059,  1006, 10060, 10061, 10062,
        10063, 10064, 10065, 10066, 10067, 10068, 10069,  1007, 10070,
        10071, 10072, 10073, 10074, 10075, 10076, 10077, 10078, 10079,
         1008, 10080, 10081, 10082, 10083]),
 array([10084, 10085, 10086, 10087, 10088, 10089,  1009, 10090, 10091,
        10092, 10093, 10094, 10095, 10096, 10097, 10098, 10099,   101,
         1010, 10100, 10101, 10102, 10103, 10104, 10105, 10106, 10107,
        10108

## process combined into wanted format

In [1]:
combined

NameError: name 'combined' is not defined